#--------------------------------------------------------------------
#       Locale
#--------------------------------------------------------------------
quarkus.default-locale=it-IT
#--------------------------------------------------------------------
#				OpenAPI and Swagger
#--------------------------------------------------------------------
%dev.quarkus.smallrye-openapi.info-title=Warehouse Logistic Optimizer
%dev.quarkus.smallrye-openapi.info-version=1.0.0
%dev.quarkus.swagger-ui.doc-expansion=none
%dev.quarkus.smallrye-openapi.path=/docs/v1/openapi
%dev.quarkus.smallrye-openapi.operation-id-strategy=method
%dev.quarkus.swagger-ui.path=/ui/v1/openapi
%dev.quarkus.swagger-ui.display-operation-id=true
%dev.quarkus.swagger-ui.always-include=true

#--------------------------------------------------------------------
#				Health
#--------------------------------------------------------------------
quarkus.smallrye-health.root-path=/api/v1/health
quarkus.smallrye-health.ui.root-path=/ui/v1/health


#--------------------------------------------------------------------
#				CORS
#--------------------------------------------------------------------
quarkus.http.cors=true
quarkus.http.cors.access-control-allow-credentials=true
quarkus.http.cors.origins=/.*/
quarkus.http.cors.methods=GET,POST,PUT,PATCH,DELETE,OPTIONS
quarkus.http.cors.headers=Authorization,Access-Control-Allow-Origin,Content-Type,Response-Type


#--------------------------------------------------------------------
#				Server properties
#--------------------------------------------------------------------
quarkus.http.root-path=/api/v1/warehouse-administrator
quarkus.http.port=8081
quarkus.http.test-port=8082


# ===========================
# Database
# ===========================
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USERNAME}
quarkus.datasource.password=${DB_PASSWORD}
quarkus.datasource.jdbc.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:warehouse_administrator}?currentSchema=${DB_SCHEMA:dev}

#--------------------------------------------------------------------
#               Flyway Migration
#--------------------------------------------------------------------
quarkus.flyway.locations=dbinit/postgres
quarkus.flyway.enabled=false
quarkus.flyway.migrate-at-start=false
quarkus.flyway.ignore-missing-migrations=false

%dev.quarkus.flyway.enabled=false
%dev.quarkus.flyway.migrate-at-start=true
%dev.quarkus.flyway.ignore-missing-migrations=false



# ===========================
# OIDC  valida token in ingresso (client pubblico, no secret)
# ===========================
quarkus.oidc.auth-server-url=${OIDC_KEYCLOAK_URL: http://localhost:8080/realms/warehouse-realm}
quarkus.oidc.client-id=${KEYCLOAK_CLIENT_ID}
quarkus.oidc.application-type=service
quarkus.oidc.roleTypes.roleType-claim-path=realm_access/roleTypes

# ===========================
# Admin Client  service account SEPARATO, solo per gestione utenti
# ===========================
quarkus.keycloak.admin-client.server-url=${KEYCLOAK_URL: http://localhost:8080}
quarkus.keycloak.admin-client.realm=${KEYCLOAK_REALM}
quarkus.keycloak.admin-client.client-id==${KEYCLOAK_CLIENT_ID}
quarkus.keycloak.admin-client.client-secret==${KEYCLOAK_CLIENT_SECRET}
quarkus.keycloak.admin-client.grant-type=client_credentials


# ===========================
# REST Client
# ===========================
quarkus.rest-client.keycloak-token.url={OIDC_KEYCLOAK_URL: http://localhost:8080/realms/warehouse-realm}

# ===========================
# CUSTOM
# ===========================
scheduler.cron=0 0 3 * * ?
scheduler.enabled=true
user-registration.expire-in-days=7