-- apply changes
create table category_type (
  description                   TEXT not null,
  id                            varchar(255) not null,
  constraint pk_category_type primary key (id)
);

create table city (
  id                            bigint generated by default as identity not null,
  region_id                     bigint not null,
  latitude                      decimal(10,7),
  longitude                     decimal(10,7),
  name                          varchar(255) not null,
  province                      varchar(3) not null,
  istat_code                    varchar(10) not null,
  constraint uq_city_istat_code unique (istat_code),
  constraint pk_city primary key (id)
);

create table movement_status_history (
  id                            bigint generated by default as identity not null,
  movement_track_id             uuid not null,
  movement_track_destination_id uuid,
  product_id                    uuid not null,
  quantity                      integer not null,
  notes                         TEXT,
  _version                      bigint not null,
  _data_creazione               timestamptz not null,
  _data_modifica                timestamptz not null,
  status                        varchar(12) not null,
  _utente_creazione             varchar(255) not null,
  _utente_modifica              varchar(255) not null,
  constraint ck_movement_status_history_status check ( status in ('SENT','RECEIVED','IN_TRANSIT','CANCELLED','FROM_FACTORY','TO_SALE')),
  constraint pk_movement_status_history primary key (id)
);

create table movement_track (
  id                            uuid not null,
  origin_warehouse_id           uuid,
  product_id                    uuid not null,
  quantity                      integer not null,
  estimated_final_date_for_final_travel timestamp,
  _version                      bigint not null,
  _data_creazione               timestamptz not null,
  _data_modifica                timestamptz not null,
  estimated_total_duration_millis decimal(12),
  estimated_total_distance_meters decimal(19,10),
  veicolo_da_implementare       varchar(255),
  _utente_creazione             varchar(255) not null,
  _utente_modifica              varchar(255) not null,
  constraint pk_movement_track primary key (id)
);

create table a_movement_track_destination (
  id                            uuid not null,
  destination_warehouse_id      uuid not null,
  movement_track_id             uuid not null,
  quantity_delivered            integer not null,
  stop_order                    integer not null,
  estimated_arrival             timestamp,
  notes                         TEXT,
  _version                      bigint not null,
  _data_creazione               timestamptz not null,
  _data_modifica                timestamptz not null,
  estimated_duration_millis     decimal(12),
  estimated_distance_meters     decimal(19,10),
  _utente_creazione             varchar(255) not null,
  _utente_modifica              varchar(255) not null,
  constraint pk_a_movement_track_destination primary key (id)
);

create table product (
  id                            uuid not null,
  name                          TEXT not null,
  volume                        float not null,
  weight                        float not null,
  _version                      bigint not null,
  _data_creazione               timestamptz not null,
  _data_modifica                timestamptz not null,
  movement_type_id              varchar(255) not null,
  _utente_creazione             varchar(255) not null,
  _utente_modifica              varchar(255) not null,
  constraint pk_product primary key (id)
);

create table region (
  id                            bigint generated by default as identity not null,
  name                          varchar(255) not null,
  istat_code                    varchar(10) not null,
  constraint uq_region_name unique (name),
  constraint uq_region_istat_code unique (istat_code),
  constraint pk_region primary key (id)
);

create table a_product_warehouse (
  id                            bigint generated by default as identity not null,
  warehouse_id                  uuid not null,
  product_id                    uuid not null,
  quantity                      integer not null,
  _version                      bigint not null,
  _data_creazione               timestamptz not null,
  _data_modifica                timestamptz not null,
  _utente_creazione             varchar(255) not null,
  _utente_modifica              varchar(255) not null,
  constraint pk_a_product_warehouse primary key (id)
);

create table warehouse (
  id                            uuid not null,
  name                          TEXT not null,
  volume_capacity               float not null,
  available_volume              float,
  weight_capacity               float not null,
  available_weight              float,
  city_id                       bigint not null,
  _version                      bigint not null,
  _data_creazione               timestamptz not null,
  _data_modifica                timestamptz not null,
  _utente_creazione             varchar(255) not null,
  _utente_modifica              varchar(255) not null,
  constraint pk_warehouse primary key (id)
);

-- foreign keys and indices
create index ix_city_region_id on city (region_id);
alter table city add constraint fk_city_region_id foreign key (region_id) references region (id) on delete restrict on update restrict;

create index ix_movement_status_history_movement_track_id on movement_status_history (movement_track_id);
alter table movement_status_history add constraint fk_movement_status_history_movement_track_id foreign key (movement_track_id) references movement_track (id) on delete restrict on update restrict;

create index ix_movement_status_history_movement_track_destination_id on movement_status_history (movement_track_destination_id);
alter table movement_status_history add constraint fk_movement_status_history_movement_track_destination_id foreign key (movement_track_destination_id) references a_movement_track_destination (id) on delete restrict on update restrict;

create index ix_movement_status_history_product_id on movement_status_history (product_id);
alter table movement_status_history add constraint fk_movement_status_history_product_id foreign key (product_id) references product (id) on delete restrict on update restrict;

create index ix_movement_track_origin_warehouse_id on movement_track (origin_warehouse_id);
alter table movement_track add constraint fk_movement_track_origin_warehouse_id foreign key (origin_warehouse_id) references warehouse (id) on delete restrict on update restrict;

create index ix_movement_track_product_id on movement_track (product_id);
alter table movement_track add constraint fk_movement_track_product_id foreign key (product_id) references product (id) on delete restrict on update restrict;

create index ix_a_movement_track_destination_destination_warehouse_id on a_movement_track_destination (destination_warehouse_id);
alter table a_movement_track_destination add constraint fk_a_movement_track_destination_destination_warehouse_id foreign key (destination_warehouse_id) references warehouse (id) on delete restrict on update restrict;

create index ix_a_movement_track_destination_movement_track_id on a_movement_track_destination (movement_track_id);
alter table a_movement_track_destination add constraint fk_a_movement_track_destination_movement_track_id foreign key (movement_track_id) references movement_track (id) on delete restrict on update restrict;

create index ix_product_movement_type_id on product (movement_type_id);
alter table product add constraint fk_product_movement_type_id foreign key (movement_type_id) references category_type (id) on delete restrict on update restrict;

create index ix_a_product_warehouse_warehouse_id on a_product_warehouse (warehouse_id);
alter table a_product_warehouse add constraint fk_a_product_warehouse_warehouse_id foreign key (warehouse_id) references warehouse (id) on delete restrict on update restrict;

create index ix_a_product_warehouse_product_id on a_product_warehouse (product_id);
alter table a_product_warehouse add constraint fk_a_product_warehouse_product_id foreign key (product_id) references product (id) on delete restrict on update restrict;

create index ix_warehouse_city_id on warehouse (city_id);
alter table warehouse add constraint fk_warehouse_city_id foreign key (city_id) references city (id) on delete restrict on update restrict;

create index if not exists ix_city_name on city (name);
create index if not exists ix_city_istat_code on city (istat_code);
create index if not exists ix_movement_status_history_status on movement_status_history (status);
create index if not exists ix_region_name on region (name);
