version: '3.8'

services:
  warehouse_logistic_db:
    image: postgres:17.2
    container_name: warehouse_logistic
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=warehouse_logistic
      - POSTGRES_USER=warehouse_logistic
      - POSTGRES_PASSWORD=warehouse_logistic
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

