-- apply changes
create table category_type (
  description                   TEXT not null,
  id                            varchar(255) not null,
  constraint pk_category_type primary key (id)
);

create table city (
  id                            bigint generated by default as identity not null,
  region_id                     bigint not null,
  latitude                      decimal(10,7),
  longitude                     decimal(10,7),
  name                          varchar(255) not null,
  province                      varchar(3) not null,
  istat_code                    varchar(10) not null,
  constraint uq_city_istat_code unique (istat_code),
  constraint pk_city primary key (id)
);

create table movement_route (
  id                            bigint generated by default as identity not null,
  movement_track_id             uuid,
  from_warehouse_id             uuid,
  to_warehouse_id               uuid,
  step_order                    integer not null,
  _version                      bigint not null,
  _data_creazione               timestamptz not null,
  _data_modifica                timestamptz not null,
  _utente_creazione             varchar(255) not null,
  _utente_modifica              varchar(255) not null,
  constraint pk_movement_route primary key (id)
);

create table movement_status_history (
  id                            bigint generated by default as identity not null,
  movement_track_id             uuid not null,
  product_id                    uuid not null,
  quantity                      integer not null,
  notes                         TEXT,
  _version                      bigint not null,
  _data_creazione               timestamptz not null,
  _data_modifica                timestamptz not null,
  status                        varchar(10) not null,
  _utente_creazione             varchar(255) not null,
  _utente_modifica              varchar(255) not null,
  constraint ck_movement_status_history_status check ( status in ('SENT','RECEIVED','IN_TRANSIT','CANCELLED')),
  constraint pk_movement_status_history primary key (id)
);

create table movementtrack (
  id                            uuid not null,
  origin_warehouse_id           uuid not null,
  destination_warehouse_id      uuid not null,
  product_id                    uuid not null,
  quantity                      integer not null,
  estimated_arrival             timestamp not null,
  _version                      bigint not null,
  _data_creazione               timestamptz not null,
  _data_modifica                timestamptz not null,
  estimated_duration_millis     decimal(12) not null,
  estimated_distance_meters     decimal(19,10) not null,
  veicolo_da_implementare       varchar(255),
  _utente_creazione             varchar(255) not null,
  _utente_modifica              varchar(255) not null,
  constraint pk_movementtrack primary key (id)
);

create table product (
  id                            uuid not null,
  name                          TEXT not null,
  volume                        float not null,
  weight                        float not null,
  _version                      bigint not null,
  _data_creazione               timestamptz not null,
  _data_modifica                timestamptz not null,
  movement_type_id              varchar(255) not null,
  _utente_creazione             varchar(255) not null,
  _utente_modifica              varchar(255) not null,
  constraint pk_product primary key (id)
);

create table region (
  id                            bigint generated by default as identity not null,
  name                          varchar(255) not null,
  istat_code                    varchar(10) not null,
  constraint uq_region_name unique (name),
  constraint uq_region_istat_code unique (istat_code),
  constraint pk_region primary key (id)
);

create table a_product_warehouse (
  id                            bigint generated by default as identity not null,
  warehouse_id                  uuid not null,
  product_id                    uuid not null,
  quantity                      integer not null,
  _version                      bigint not null,
  _data_creazione               timestamptz not null,
  _data_modifica                timestamptz not null,
  _utente_creazione             varchar(255) not null,
  _utente_modifica              varchar(255) not null,
  constraint pk_a_product_warehouse primary key (id)
);

create table warehouse (
  id                            uuid not null,
  name                          TEXT not null,
  volume_capacity               float not null,
  weight_capacity               float not null,
  city_id                       bigint not null,
  _version                      bigint not null,
  _data_creazione               timestamptz not null,
  _data_modifica                timestamptz not null,
  _utente_creazione             varchar(255) not null,
  _utente_modifica              varchar(255) not null,
  constraint pk_warehouse primary key (id)
);

-- foreign keys and indices
create index ix_city_region_id on city (region_id);
alter table city add constraint fk_city_region_id foreign key (region_id) references region (id) on delete restrict on update restrict;

create index ix_movement_route_movement_track_id on movement_route (movement_track_id);
alter table movement_route add constraint fk_movement_route_movement_track_id foreign key (movement_track_id) references movementtrack (id) on delete restrict on update restrict;

create index ix_movement_route_from_warehouse_id on movement_route (from_warehouse_id);
alter table movement_route add constraint fk_movement_route_from_warehouse_id foreign key (from_warehouse_id) references warehouse (id) on delete restrict on update restrict;

create index ix_movement_route_to_warehouse_id on movement_route (to_warehouse_id);
alter table movement_route add constraint fk_movement_route_to_warehouse_id foreign key (to_warehouse_id) references warehouse (id) on delete restrict on update restrict;

create index ix_movement_status_history_movement_track_id on movement_status_history (movement_track_id);
alter table movement_status_history add constraint fk_movement_status_history_movement_track_id foreign key (movement_track_id) references movementtrack (id) on delete restrict on update restrict;

create index ix_movement_status_history_product_id on movement_status_history (product_id);
alter table movement_status_history add constraint fk_movement_status_history_product_id foreign key (product_id) references product (id) on delete restrict on update restrict;

create index ix_movementtrack_origin_warehouse_id on movementtrack (origin_warehouse_id);
alter table movementtrack add constraint fk_movementtrack_origin_warehouse_id foreign key (origin_warehouse_id) references warehouse (id) on delete restrict on update restrict;

create index ix_movementtrack_destination_warehouse_id on movementtrack (destination_warehouse_id);
alter table movementtrack add constraint fk_movementtrack_destination_warehouse_id foreign key (destination_warehouse_id) references warehouse (id) on delete restrict on update restrict;

create index ix_movementtrack_product_id on movementtrack (product_id);
alter table movementtrack add constraint fk_movementtrack_product_id foreign key (product_id) references product (id) on delete restrict on update restrict;

create index ix_product_movement_type_id on product (movement_type_id);
alter table product add constraint fk_product_movement_type_id foreign key (movement_type_id) references category_type (id) on delete restrict on update restrict;

create index ix_a_product_warehouse_warehouse_id on a_product_warehouse (warehouse_id);
alter table a_product_warehouse add constraint fk_a_product_warehouse_warehouse_id foreign key (warehouse_id) references warehouse (id) on delete restrict on update restrict;

create index ix_a_product_warehouse_product_id on a_product_warehouse (product_id);
alter table a_product_warehouse add constraint fk_a_product_warehouse_product_id foreign key (product_id) references product (id) on delete restrict on update restrict;

create index ix_warehouse_city_id on warehouse (city_id);
alter table warehouse add constraint fk_warehouse_city_id foreign key (city_id) references city (id) on delete restrict on update restrict;

create index if not exists ix_city_name on city (name);
create index if not exists ix_city_istat_code on city (istat_code);
create index if not exists ix_region_name on region (name);
